meta_product_name: "VeraCity"
meta_title: "VeraCity - Are you a purchaser? Need to quickly find and buy medical equipment/PPE? Don't know where to go or who to trust? We're the solution for you with Trusted Suppliers™"
meta_description: "Bringing you Trusted Suppliers™"
meta_image: "logo.png"
twitter_account: "@VeraCity_Asia"
